import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { montserrat } from "@/utils/fonts";
import Sidebar from "@/components/Sidebar";
import UserService from "@/services/user.service";
import { RafoUserProvider } from "@/context/RafoAuthContext";
import "./globals.css";
import { getSession, Session } from "@auth0/nextjs-auth0";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session = await getSession();
  let user;
  if (session){
    const { user: claims, accessToken } = session;
    console.log(accessToken);
    user = await UserService.getMe(claims, accessToken);
    console.log(user);
  }
  return (
    <html lang="en">
      <UserProvider>
        <RafoUserProvider>
          <body className={`${montserrat.className} antialiased bg-background`}>
            <div className="">
              <Sidebar user={user}/>
              <main className="ml-16 relative">{children}</main>
              <Toaster />
            </div>
          </body>
        </RafoUserProvider>
      </UserProvider>
    </html>
  );
}

// How to kill your children (?)
